apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tz8xorzpa-nodejs 
  janus-idp.io/tekton: tz8xorzpa-nodejs
  backstage.io/kubernetes-id: tz8xorzpa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tz8xorzpa-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  