apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tz8xorzpa-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tz8xorzpa-nodejs 
  name: tz8xorzpa-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tz8xorzpa-nodejs 
